### ISSUE TITLE
Сборка робота

### ISSUE THREAD

**Issue by zakolm** [zakolm/project_for_park_mail_c#3]
# Сборка прототипа робота
Сборка и проверка минимальных движений робота.

**Comment by ghost** [comment]
Первый экземпляр робота-ищейки представлял из себя устройство на основе платы arduino uno, было разделено питание для платы и для моторов. Два ведущих колеса, соединенных через motorshild c arduino uno и подшипник вместо задних колес. Прототип 1 работал нестабильно, не ехал по прямой (сворачивал в сторону). Регулировка скорости вращения моторов помогала, но время от времени один мотор просто переставал работать. Ультразвуковой датчик был статично закреплен на передней части робота.
